# Generated by Django 4.1.7 on 2023-07-29 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seller', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('review', models.TextField(blank=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Аватарка')),
                ('city', models.CharField(blank=True, choices=[('ekb', 'Экибастуз'), ('pvl', 'Павлодар'), ('asn', 'Астана')], max_length=3)),
                ('phone', models.IntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
