# Generated by Django 4.2.2 on 2023-06-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('ekb', 'Экибастуз'), ('pvl', 'Павлодар'), ('asn', 'Астана')], max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
