# Generated by Django 4.2.1 on 2023-05-21 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_posts', to='Blog.posts', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='cat_post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Blog.category', verbose_name='Категории'),
        ),
    ]
