# Generated by Django 4.1.7 on 2023-06-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_comments_article_alter_posts_cat_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Видимость статьи'),
        ),
    ]
