# Generated by Django 4.2.2 on 2023-06-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_posts_city_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='images',
            field=models.ManyToManyField(to='Blog.image'),
        ),
    ]
