# Generated by Django 4.2.2 on 2023-06-19 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_remove_image_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.posts')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='posts',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='posts', to='Blog.customimage'),
        ),
    ]
