# Generated by Django 4.2.2 on 2023-06-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_remove_posts_images_posts_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='images',
        ),
        migrations.AddField(
            model_name='posts',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='posts', to='Blog.customimage'),
        ),
    ]
