# Generated by Django 4.2.2 on 2023-06-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_alter_customimage_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customimage',
            name='post',
        ),
        migrations.AlterField(
            model_name='posts',
            name='images',
            field=models.ManyToManyField(blank=True, to='Blog.customimage'),
        ),
    ]
