# Generated by Django 4.2.2 on 2023-06-23 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0014_remove_customimage_post_alter_posts_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.posts'),
        ),
    ]
