# Generated by Django 4.2.2 on 2023-06-23 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_customimage_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='images',
        ),
    ]
